=== growthcharts/bdsreader/inst/schemas/bds_v3.0.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/growthcharts/bdsreader/srm/inst/schemas/bds_v3.0.json",
  "type": "object",
  "title": "JAMES input data specification",
  "required": [
    "Format",
    "clientDetails"
  ],
  "properties": {
    "reference": {
      "title": "Request identification",
      "$id": "#/properties/reference",
      "type": "string",
      "pattern": "^(.*)$"
    },
    "Format": {
      "title": "Schema version number",
      "$id": "#/properties/Format",
      "type": "string",
      "pattern": "[0-9]+\\.[0-9]+"
    },
    "organisationCode": {
      "title": "Care organisation code",
      "$id": "#/properties/organisationCode",
      "type": "integer"
    },
    "clientDetails": {
      "title": "Child data object",
      "type": "array",
      "allOf": [
        {
          "contains": {
            "properties": {
              "bdsNumber": {
                "const": 19
              }
            }
          }
        },
        {
          "contains": {
            "properties": {
              "bdsNumber": {
                "const": 20
              }
            }
          }
        }
      ],
      "items": {
        "$ref": "#/schemas/clientDetails"
      }
    },
    "clientMeasurements": {
      "title": "Child data per visit",
      "$id": "#/properties/clientMeasurements",
      "type": "array",
      "items": {
        "$ref": "#/schemas/clientMeasurements"
      }
    },
    "nestedDetails": {
      "title": "Child data per visit",
      "$id": "#/properties/nestedDetails",
      "type": "array",
      "items": {
        "required": ["nestingBdsNumber", "nestingCode"],
        "properties": {
        "clientDetails": {
        	"items": {
        		"$ref": "#/schemas/clientDetails"
      		}
        },
        "clientMeasurements": {
        	"items": {
        		"$ref": "#/schemas/clientMeasurements"
      		}
        }
        }
      }
    }
  },
  "$defs": {
    "clientDetails": {
      "$id": "#/schemas/clientDetails",
      "required": [
        "bdsNumber"
      ],
      "if": {
        "properties": {
          "bdsNumber": {"enum": [16, 19, 20, 62, 63, 66, 71, 82, 91, 110, 238, 240, 471, 510]}
        }
      },
      "then": {
        "anyOf": [
          {
            "properties": {
              "bdsNumber": {
                "const": 16
              },
              "value": {
                "type": "string",
                "pattern": "^([0-9]{4})$"
              }
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "const": 19
              },
              "value": {"enum": ["0", "1", "2", "3"]}
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "enum": [20, 63]
              },
              "value": {"pattern": "^([0-9]{8})$"}
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "const": 62
              },
              "value": {"enum": ["01", "02", "03", "04", "05", "06", "07", "08", "98"]}
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "const": 66
              },
              "value": {"enum": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "98", "00"]}
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "const": 71
              },
              "value": {
                "type": "number",
                "minimum": 1000,
                "maximum": 9999
              }
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "const": 82
              },
              "value": {
                "type": "number",
                "minimum": 50,
                "maximum": 350
              }
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "const": 91
              },
              "value": {"enum": ["1", "2", "99"]}
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "const": 110
              },
              "value": {
                "type": "number",
                "minimum": 300,
                "maximum": 9999
              }
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "enum": [238, 240]
              },
              "value": {
                "type": "number",
                "minimum": 100,
                "maximum": 2500
              }
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "const": 471
              },
              "value": {
                "type": "number",
                "minimum": 0,
                "maximum": 25
              }
            }
          }
        ]
      }
    }
    ,
    "clientMeasurements": {
      "$id": "#/schemas/clientMeasurements",
      "required": [
        "bdsNumber"
      ],
      "properties": {
        "values": {
          "items": {
            "properties": {
              "date": {
                "type": "string",
                "pattern": "^([0-9]{8})$"
              }
            }
          }
        }
      },
      "if": {
        "properties": {
          "bdsNumber": {
            "enum": [235, 245, 252, 510, 879, 881, 883, 884, 885, 887, 888, 889, 890, 891, 894, 896, 897, 898, 902, 903, 906, 907, 910, 912, 914, 916, 917, 918, 920, 922, 923, 926, 945, 951, 955, 956, 958, 959, 961, 962, 964, 966, 968, 970, 971, 973, 975, 977, 978, 986, 989, 991, 993, 994, 996, 999, 1002, 886, 892, 893, 900, 905, 909, 913, 921, 927, 928, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 943, 947, 948, 949, 950, 953, 954, 972, 980, 982, 984, 998, 1001, 1278]
          }
        }
      },
      "then": {
        "anyOf": [
          {
            "properties": {
              "bdsNumber": {
                "enum": [235, 245]
              },
              "values": {
                "type": "array",
                "items": {
                  "properties": {
                    "value": {
                      "type": "number",
                      "minimum": 100,
                      "maximum": 300000
                    }
                  }
                }
              }
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "const": 252
              },
              "values": {
                "type": "array",
                "items": {
                  "properties": {
                    "value": {
                      "type": "number",
                      "minimum": 100,
                      "maximum": 9999
                    }
                  }
                }
              }
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "const": 510
              },
              "values": {
                "type": "array",
                "items": {
                  "properties": {
                    "value": {"enum": ["01", "02", "03", "04"]}
                  }
                }
              }
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "enum": [879, 881, 883, 884, 885, 887, 888, 889, 890, 891, 894, 896, 897, 898, 902, 903, 906, 907, 910, 912, 914, 916, 917, 918, 920, 922, 923, 926, 945, 951, 955, 956, 958, 959, 961, 962, 964, 966, 968, 970, 971, 975, 977, 978, 986, 989, 991, 993, 994, 996, 999, 1001, 1002]
              },
              "values": {
                "type": "array",
                "items": {
                  "properties": {
                    "value": { "enum": ["1", "2"]}
                  }
                }
              }
            }
          },
          {
            "properties": {
              "bdsNumber": {
                "enum": [886, 892, 893, 900, 905, 909, 913, 921, 927, 928, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 943, 947, 948, 949, 950, 953, 954, 972, 973, 980, 982, 984, 998, 1278]
              },
              "values": {
                "type": "array",
                "items": {
                  "properties": {
                    "value": {"enum": ["1", "2", "3"]}
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

=== growthcharts/bdsreader/inst/examples/Kevin_S.json
{
  "Format": "3.0",
  "organisationCode": 0,
  "reference": "Kevin S",
  "clientDetails": [
    {
      "bdsNumber": 19,
      "value": "1"
    },
    {
      "bdsNumber": 20,
      "value": "19890214"
    },
    {
      "bdsNumber": 82,
      "value": 241
    },
    {
      "bdsNumber": 91,
      "value": "2"
    },
    {
      "bdsNumber": 110,
      "value": 1740
    },
    {
      "bdsNumber": 238,
      "value": 1680
    },
    {
      "bdsNumber": 240,
      "value": 1780
    }
  ],
  "clientMeasurements": [
    {
      "bdsNumber": 235,
      "values": [
        {
          "date": "19890214",
          "value": 430
        },
        {
          "date": "19890405",
          "value": 500
        },
        {
          "date": "19890419",
          "value": 515
        },
        {
          "date": "19890517",
          "value": 555
        },
        {
          "date": "19890816",
          "value": 650
        },
        {
          "date": "19891115",
          "value": 710
        },
        {
          "date": "19900221",
          "value": 755
        },
        {
          "date": "19900523",
          "value": 770
        },
        {
          "date": "19900821",
          "value": 810
        },
        {
          "date": "19910219",
          "value": 880
        }
      ]
    },
    {
      "bdsNumber": 245,
      "values": [
        {
          "date": "19890214",
          "value": 1740
        },
        {
          "date": "19890405",
          "value": 2880
        },
        {
          "date": "19890419",
          "value": 3280
        },
        {
          "date": "19890517",
          "value": 4170
        },
        {
          "date": "19890816",
          "value": 6220
        },
        {
          "date": "19891115",
          "value": 7310
        },
        {
          "date": "19900221",
          "value": 8240
        },
        {
          "date": "19900523",
          "value": 9000
        },
        {
          "date": "19900821",
          "value": 9550
        },
        {
          "date": "19910219",
          "value": 10900
        }
      ]
    },
    {
      "bdsNumber": 252,
      "values": [
        {
          "date": "19890214",
          "value": 320
        },
        {
          "date": "19890405",
          "value": 337
        },
        {
          "date": "19890419",
          "value": 346
        },
        {
          "date": "19890517",
          "value": 360
        },
        {
          "date": "19890816",
          "value": 393
        },
        {
          "date": "19891115",
          "value": 420
        },
        {
          "date": "19900221",
          "value": 431
        },
        {
          "date": "19900523",
          "value": 440
        },
        {
          "date": "19900821",
          "value": 440
        },
        {
          "date": "19910219",
          "value": 465
        }
      ]
    },
    {
      "bdsNumber": 879,
      "values": [
        {
          "date": "19890405",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 881,
      "values": [
        {
          "date": "19890405",
          "value": "2"
        },
        {
          "date": "19890419",
          "value": "2"
        },
        {
          "date": "19890517",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 883,
      "values": [
        {
          "date": "19890405",
          "value": "2"
        },
        {
          "date": "19890419",
          "value": "2"
        },
        {
          "date": "19890517",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 884,
      "values": [
        {
          "date": "19890405",
          "value": "1"
        },
        {
          "date": "19890419",
          "value": "1"
        },
        {
          "date": "19890517",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 885,
      "values": [
        {
          "date": "19890405",
          "value": "1"
        },
        {
          "date": "19890419",
          "value": "1"
        },
        {
          "date": "19890517",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 886,
      "values": [
        {
          "date": "19890419",
          "value": "2"
        },
        {
          "date": "19890517",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 887,
      "values": [
        {
          "date": "19890816",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 888,
      "values": [
        {
          "date": "19890816",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 889,
      "values": [
        {
          "date": "19890816",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 890,
      "values": [
        {
          "date": "19890816",
          "value": "2"
        },
        {
          "date": "19891115",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 891,
      "values": [
        {
          "date": "19890816",
          "value": "2"
        },
        {
          "date": "19891115",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 892,
      "values": [
        {
          "date": "19890816",
          "value": "3"
        },
        {
          "date": "19891115",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 893,
      "values": [
        {
          "date": "19890816",
          "value": "3"
        },
        {
          "date": "19891115",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 894,
      "values": [
        {
          "date": "19891115",
          "value": "2"
        },
        {
          "date": "19900221",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 896,
      "values": [
        {
          "date": "19891115",
          "value": "2"
        },
        {
          "date": "19900221",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 897,
      "values": [
        {
          "date": "19900221",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 898,
      "values": [
        {
          "date": "19900221",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 900,
      "values": [
        {
          "date": "19900221",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 902,
      "values": [
        {
          "date": "19900523",
          "value": "1"
        },
        {
          "date": "19900821",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 903,
      "values": [
        {
          "date": "19900523",
          "value": "1"
        },
        {
          "date": "19900821",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 905,
      "values": [
        {
          "date": "19900523",
          "value": "3"
        },
        {
          "date": "19900821",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 906,
      "values": [
        {
          "date": "19900821",
          "value": "1"
        },
        {
          "date": "19910219",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 909,
      "values": [
        {
          "date": "19900821",
          "value": "3"
        },
        {
          "date": "19910219",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 910,
      "values": [
        {
          "date": "19910219",
          "value": "2"
        }
      ]
    },
    {
      "bdsNumber": 912,
      "values": [
        {
          "date": "19910219",
          "value": "2"
        }
      ]
    },
    {
      "bdsNumber": 921,
      "values": [
        {
          "date": "19910219",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 927,
      "values": [
        {
          "date": "19890405",
          "value": "1"
        }
      ]
    },
    {
      "bdsNumber": 928,
      "values": [
        {
          "date": "19890405",
          "value": "2"
        },
        {
          "date": "19890419",
          "value": "2"
        },
        {
          "date": "19890517",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 930,
      "values": [
        {
          "date": "19890419",
          "value": "2"
        },
        {
          "date": "19890517",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 932,
      "values": [
        {
          "date": "19890816",
          "value": "2"
        },
        {
          "date": "19891115",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 933,
      "values": [
        {
          "date": "19891115",
          "value": "3"
        },
        {
          "date": "19900221",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 935,
      "values": [
        {
          "date": "19891115",
          "value": "2"
        },
        {
          "date": "19900221",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 936,
      "values": [
        {
          "date": "19900221",
          "value": "2"
        },
        {
          "date": "19900523",
          "value": "2"
        },
        {
          "date": "19900821",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 937,
      "values": [
        {
          "date": "19900221",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 938,
      "values": [
        {
          "date": "19900523",
          "value": "2"
        },
        {
          "date": "19900821",
          "value": "2"
        },
        {
          "date": "19910219",
          "value": "3"
        }
      ]
    },
    {
      "bdsNumber": 940,
      "values": [
        {
